export const PRODUCT_SUCCESS = 'DISPLAY__PRODUCTS'
export const ADD_TO_CART_LIST = 'ADD__TO__CART__LIST'
export const ADD_TO_CART_WISHLIST = 'ADD__TO__WISH'
export const REMOVE_SINGLE_ITEM = 'REMOVE__SINGLE__ITEM__FROM__CART'

export const REMOVE_SINGLE_FROM_WISHLIST = 'REMOVE__SINGLE__ITEM__FROM__THE__WISHLIST'

export const SET_TOTAL_PRICE = 'TOTAL_PRICE_ALL_OF_THEM'
export const INCREACE_QUANTITY = 'INCREACE_SINGLE_ITEM_QUANTITY'
export const DECREACE_QUANTITY = 'DECREACE__SINGLE__ITEM__QUANTITY'


export const ADD_TO_CART_LIST_FROM_SINGLE_DETAILS = 'ADD__TO__CART__LIST__FROM__SINGEL_ITEM__DETAILS'

export const INCREACE_DETAILS_SINGLEI_ITEM = 'INCREACE_DETAILS_SPECIFIC_SINGEL_ITEM'
export const DECREACE_DETAILS_SINGLEI_ITEM = 'DECREACE_DETAILS_SPECIFIC_SINGEL_ITEM'

export const SHOW_ONLY_SINGLE = 'SHOW__SINGLE__PRODUCTS__DETAILS'

